FROM node:20.3.0 as builder

RUN mkdir /app
WORKDIR /app

# COPY . /app

# RUN npm install
# RUN npx webpack build

# RUN mkdir -p /app/dist/assets
# COPY ./src/assets/ /app/dist/assets/


CMD ["sh", "-c", "npm install && npm run build && npm run start"]