# Generated by Django 5.0.6 on 2024-07-04 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(unique=True)),
                ('pwd_hash', models.TextField(blank=True, null=True)),
                ('pwd_salt', models.TextField(blank=True, null=True)),
                ('session_token', models.TextField(blank=True, null=True)),
                ('session_token_expires', models.DateTimeField(blank=True, null=True)),
                ('oauth_token', models.TextField(blank=True, null=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('oauth_id', models.TextField(blank=True, null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
            ],
        ),
    ]
