# Generated by Django 5.0 on 2024-08-25 21:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcknowledgedMatchRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ball_color', models.CharField(max_length=50)),
                ('fast', models.BooleanField(default=False)),
                ('is_bot', models.BooleanField(default=False)),
                ('match_key', models.CharField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_partie', models.DateTimeField(default=django.utils.timezone.now)),
                ('duree_partie', models.IntegerField()),
                ('score_joueur1', models.IntegerField()),
                ('score_joueur2', models.IntegerField()),
                ('is_ai_opponent', models.BooleanField(default=False)),
                ('ai_opponent_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameSearchQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MatchRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ball_color', models.CharField(max_length=50)),
                ('fast', models.BooleanField(default=False)),
                ('created_at', models.FloatField()),
                ('match_key', models.CharField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='jwtuser',
            name='avatar',
            field=models.ImageField(default='default_avatar.png', max_length=200, upload_to='avatars'),
        ),
        migrations.AddField(
            model_name='jwtuser',
            name='blocked_users',
            field=models.ManyToManyField(blank=True, related_name='blocked_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jwtuser',
            name='friend_requests',
            field=models.ManyToManyField(blank=True, related_name='pending_friend_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jwtuser',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='user_friends', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jwtuser',
            name='isoauth',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jwtuser',
            name='status',
            field=models.CharField(default='Offline', max_length=20),
        ),
        migrations.AlterField(
            model_name='jwtuser',
            name='first_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='jwtuser',
            name='last_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name='acknowledgedmatchrequest',
            name='request_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acknowledged_match_requests_authored', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='acknowledgedmatchrequest',
            name='target_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_match_requests_targeted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gamehistory',
            name='gagnant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parties_gagnees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gamehistory',
            name='joueur1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parties_joueur1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gamehistory',
            name='joueur2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parties_joueur2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gamesearchqueue',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='search_queue', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='matchrequest',
            name='request_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_requests_authored', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='matchrequest',
            name='target_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_requests_targeted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
