# Generated by Django 5.0.6 on 2024-07-17 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jwtuser',
            name='isoauth',
            field=models.BooleanField(default=False),
        ),
    ]
