# Generated by Django 5.0.6 on 2024-07-03 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='oauth_id',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
