# Generated by Django 5.0.6 on 2024-06-12 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_user_pwd_hash_alter_user_pwd_salt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='session_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
