# Generated by Django 5.0 on 2024-08-02 17:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_jwtuser_avatar_jwtuser_blocked_users_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jwtuser',
            name='avatar',
            field=models.ImageField(default='default_avatar.png', max_length=200, upload_to='avatars'),
        ),
        migrations.CreateModel(
            name='GameHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_partie', models.DateTimeField(default=django.utils.timezone.now)),
                ('duree_partie', models.IntegerField()),
                ('score_joueur1', models.IntegerField()),
                ('score_joueur2', models.IntegerField()),
                ('gagnant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parties_gagnees', to=settings.AUTH_USER_MODEL)),
                ('joueur1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parties_joueur1', to=settings.AUTH_USER_MODEL)),
                ('joueur2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parties_joueur2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
