# Generated by Django 5.0 on 2024-08-06 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_jwtuser_avatar_jwtuser_blocked_users_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcknowledgedMatchRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ball_color', models.CharField(max_length=50)),
                ('fast', models.BooleanField(default=False)),
                ('is_bot', models.BooleanField(default=False)),
                ('request_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acknowledged_match_requests_authored', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_match_requests_targeted', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MatchRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ball_color', models.CharField(max_length=50)),
                ('fast', models.BooleanField(default=False)),
                ('created_at', models.FloatField()),
                ('request_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_requests_authored', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_requests_targeted', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
