# Generated by Django 5.0 on 2024-08-27 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_acknowledgedmatchrequest_author_nickname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='all_participants_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tournament',
            name='subscribed_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gamesearchqueue',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='game_search_queue', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TournamentSearchQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_search_queue', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
