# Generated by Django 5.0.6 on 2024-07-22 19:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_user_blocked_users_user_friend_requests_user_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='jwtuser',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='user_friends', to=settings.AUTH_USER_MODEL),
        ),
    ]
