# Generated by Django 5.0 on 2024-08-27 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_acknowledgedmatchrequest_author_nickname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jwtuser',
            name='first_name',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='jwtuser',
            name='last_name',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='jwtuser',
            name='username',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
