# Generated by Django 5.0 on 2024-08-30 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_jwtuser_first_name_alter_jwtuser_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='game_history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='tournament',
            name='matches_paired',
            field=models.IntegerField(default=0),
        ),
    ]
