# Generated by Django 5.0.6 on 2024-07-23 06:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_jwtuser_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='jwtuser',
            name='friend_requests',
            field=models.ManyToManyField(blank=True, related_name='pending_friend_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
