# Generated by Django 5.0 on 2024-08-27 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_jwtuser_first_name_alter_jwtuser_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jwtuser',
            name='password',
            field=models.CharField(max_length=30),
        ),
    ]
