# Generated by Django 5.0 on 2024-08-27 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_jwtuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jwtuser',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
