# Generated by Django 5.0.6 on 2024-07-23 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_remove_user_blocked_users_jwtuser_blocked_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='friend_requests',
        ),
    ]
