# Generated by Django 5.0 on 2024-08-27 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_tournamentsearchqueue_nickname'),
        ('backend', '0007_alter_jwtuser_password'),
    ]

    operations = [
    ]
