# Generated by Django 5.0.6 on 2024-07-26 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_remove_user_friend_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='jwtuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
