# Generated by Django 5.0 on 2024-08-18 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_alter_jwtuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jwtuser',
            name='avatar',
            field=models.ImageField(default='staticfiles/avatars/avatar.png', max_length=200, upload_to='staticfiles/avatars/'),
        ),
    ]
