# Generated by Django 5.0 on 2024-08-01 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jwtuser',
            name='first_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='jwtuser',
            name='last_name',
            field=models.CharField(max_length=255),
        ),
    ]
