# Generated by Django 5.0 on 2024-08-23 07:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_alter_jwtuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamehistory',
            name='ai_opponent_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gamehistory',
            name='is_ai_opponent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gamehistory',
            name='joueur2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parties_joueur2', to=settings.AUTH_USER_MODEL),
        ),
    ]
