# Generated by Django 5.0 on 2024-08-23 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_gamehistory_ai_opponent_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamehistory',
            name='joueur1_avatar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gamehistory',
            name='joueur2_avatar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
