# Generated by Django 5.0 on 2024-08-23 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_gamehistory_joueur1_avatar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamehistory',
            name='joueur1_avatar',
        ),
        migrations.RemoveField(
            model_name='gamehistory',
            name='joueur2_avatar',
        ),
    ]
