CREATE DATABASE IF NOT EXISTS ${DB_NAME};

/* Tables are managed by django */
/*CREATE TABLE IF NOT EXISTS ${TABLE_NAME} (

);*/

CREATE USER IF NOT EXISTS ${DB_USER} WITH PASSWORD '${DB_PASSWORD}';

GRANT ALL PRIVILEGES ON DATABASE ${DB_NAME} TO ${DB_USER};