export const login = {
	en: {
	  title: "Login",
	  username: "Login",
	  password: "Password",
	  loginButton: "Login",
	  or: "Or",
	  signInWith42: "Sign In with 42",
	  noAccount: "Don't have account ?",
	  signUp: "Sign Up",
	  language: "Language",
	  profile: "Profile",
	  logout: "Logout",
	  flag: "🇬🇧"
	},
	fr: {
	  title: "Connexion",
	  username: "Identifiant",
	  password: "Mot de passe",
	  loginButton: "Se connecter",
	  or: "Ou",
	  signInWith42: "Se connecter avec 42",
	  noAccount: "Vous n'avez pas de compte ?",
	  signUp: "S'inscrire",
	  language: "Langue",
	  profile: "Profil",
	  logout: "Déconnexion",
	  flag: "🇫🇷"
	},
	es: {
	  title: "Iniciar sesión",
	  username: "Usuario",
	  password: "Contraseña",
	  loginButton: "Iniciar sesión",
	  or: "O",
	  signInWith42: "Iniciar sesión con 42",
	  noAccount: "¿No tienes cuenta?",
	  signUp: "Registrarse",
	  language: "Idioma",
	  profile: "Perfil",
	  logout: "Cerrar sesión",
	  flag: "🇪🇸"
	}
  };


  export const home = {
    en: {
        profile: "Profile",
        logout: "Logout",
		blocked: "Blocked",
    	noBlockedUsers: "No blocked users found.",
    	messagePlaceholder: "Message",
    	addFriendsPrompt: "You can add friends with their username.",
    	usernamePlaceholder: "Username",
    	block: "Block",
    	blockConfirmation: "Are you sure you want to block this user? Blocking this user will also remove them from your friends list.",
    	cancel: "Cancel",
    	noFriendsFound: "No friends found.",
    	pending: "Pending",
    	noPendingRequests: "No pending friend requests.",
		friends: "Friends",
		pending: "Pending",
		blocked: "Blocked",
		online: "Online",
		tournament: "Tournament",
		gameSettings: "Game Settings",
		fastBallSpeed: "Fast Ball Speed",
		defaultSpeedMessage: "By default the speed of the ball is set to normal",
		black: "Black",
		blue: "Blue",
		red: "Red",
		defaultColorMessage: "By default color of the ball is set to Black",
		cancel: "Cancel",
		play: "Play",
		nickname: "Nickname",
		enterNicknameMessage: "Please enter a Nickname for the tournament",
		aiPlayers: "AI Players",
		noAiPlayersMessage: "No AI players added. Add some!",
		aiNickname: "AI Nickname",
		enterAiNicknameMessage: "Please enter a Nickname for the AI",
       
    },
    fr: {
        profile: "Profil",
        logout: "Déconnexion",
		blocked: "Bloqué",
    	noBlockedUsers: "Aucun utilisateur bloqué trouvé.",
    	messagePlaceholder: "Message",
    	addFriendsPrompt: "Vous pouvez ajouter des amis avec leur nom d'utilisateur.",
    	usernamePlaceholder: "Nom d'utilisateur",
    	block: "Bloquer",
    	blockConfirmation: "Êtes-vous sûr de vouloir bloquer cet utilisateur ? Le bloquer le supprimera également de votre liste d'amis.",
    	cancel: "Annuler",
    	noFriendsFound: "Aucun ami trouvé.",
    	pending: "En attente",
    	noPendingRequests: "Aucune demande d'ami en attente.",
		friends: "Amis",
		pending: "En attente",
		blocked: "Bloqués",
		online: "En ligne",
		tournament: "Tournoi",
		gameSettings: "Paramètres du jeu",
		fastBallSpeed: "Vitesse de balle rapide",
		defaultSpeedMessage: "Par défaut, la vitesse de la balle est réglée sur normal",
		black: "Noir",
		blue: "Bleu",
		red: "Rouge",
		defaultColorMessage: "Par défaut, la couleur de la balle est réglée sur Noir",
		cancel: "Annuler",
		play: "Jouer",
		nickname: "Pseudo",
		enterNicknameMessage: "Veuillez entrer un pseudo pour le tournoi",
		aiPlayers: "Joueurs IA",
		noAiPlayersMessage: "Aucun joueur IA ajouté. Ajoutez-en !",
		aiNickname: "Pseudo IA",
		enterAiNicknameMessage: "Veuillez entrer un pseudo pour l'IA",
        
    },
    es: {
        profile: "Perfil",
        logout: "Cerrar sesión",
		blocked: "Bloqueado",
    	noBlockedUsers: "No se encontraron usuarios bloqueados.",
    	messagePlaceholder: "Mensaje",
    	addFriendsPrompt: "Puedes añadir amigos con su nombre de usuario.",
    	usernamePlaceholder: "Nombre de usuario",
    	block: "Bloquear",
    	blockConfirmation: "¿Estás seguro de que quieres bloquear a este usuario? Bloquear a este usuario también lo eliminará de tu lista de amigos.",
    	cancel: "Cancelar",
    	noFriendsFound: "No se encontraron amigos.",
    	pending: "Pendiente",
    	noPendingRequests: "No hay solicitudes de amistad pendientes.",
		friends: "Amigos",
		pending: "Pendientes",
		blocked: "Bloqueados",
		online: "En línea",
		tournament: "Torneo",
		gameSettings: "Configuración del juego",
		fastBallSpeed: "Velocidad de bola rápida",
		defaultSpeedMessage: "Por defecto, la velocidad de la bola está configurada en normal",
		black: "Negro",
		blue: "Azul",
		red: "Rojo",
		defaultColorMessage: "Por defecto, el color de la bola está configurado en Negro",
		cancel: "Cancelar",
		play: "Jugar",
		nickname: "Apodo",
		enterNicknameMessage: "Por favor, ingrese un apodo para el torneo",
		aiPlayers: "Jugadores IA",
		noAiPlayersMessage: "No se han añadido jugadores IA. ¡Añade algunos!",
		aiNickname: "Apodo IA",
		enterAiNicknameMessage: "Por favor, ingrese un apodo para la IA",
    }
};