export const home = {
	en: {
	  title: "Home",
	  aiMaxPlayers: "Maximum number of AI players reached.",
	  lookForGame: "Look for a Game",
	  createTournament: "Create Tournament",
	  createGame: "Create Game",
	  joinTournament: "Join Tournament",
	  online: "Online",
	  settingsGameTitle: "Settings of the Game",
	  fastBallSpeed: "Fast Ball Speed",
	  aiOpponentDescription: "By default the AI opponent is set to OFF",
	  aiOpponent: "AI Opponent",
	  ballColor: "Ball Color",
	  black: "Black",
	  blue: "Blue",
	  red: "Red",
	  cancel: "Cancel",
	  play: "Play",
	  nickname: "Nickname",
	  aiNickname: "AI Nickname",
	  title: "Transcendence",
	  profile: "Profile",
	  logout: "Logout",
	  friends: "Friends",
	  pending: "Pending",
	  blocked: "Blocked",
	  aiNicknameCannotBeEmpty: "AI nickname cannot be empty.",
	  aiNicknameAlreadyUsed: "This AI nickname is already used. Please choose another one.",
	  invalidNicknameInput: "Invalid input: Nickname cannot be the same as AI nicknames.",
	  emptyNicknameError: "Invalid input: Nickname can't be empty",
	  serverError: "Incorrect input or server error. Please try again.",
	  settingsGameTitle: "Settings of the Game",
	  nickname: "Nickname",
	  enterNicknameForTournament: "Please enter a Nickname for the tournament",
	  fastBallSpeed: "Fast Ball Speed",
	  fastBallSpeedDescription: "By default the speed of the ball is set to normal",
	  black: "Black",
	  blue: "Blue",
	  red: "Red",
	  ballColorDescription: "By default color of the ball is set to Black",
      aiPlayers: "AI Players",
	  noAiPlayersAdded: "No AI players added. Add some!",
	  aiNickname: "AI Nickname",
	  enterNicknameForAi: "Please enter a Nickname for the AI",
	  cancel: "Cancel",
	  play: "Play",
	  next: "Next",
	  aiNicknameCannotBeEmpty: "AI nickname cannot be empty.",
	  aiNicknameAlreadyUsed: "This AI nickname is already used. Please choose another one.",
	  invalidNicknameInput: "Invalid input: Nickname cannot be the same as AI nicknames.",
	  emptyNicknameError: "Invalid input: Nickname can't be empty",
	  serverError: "Incorrect input or server error. Please try again.",
	  addFriendsTitle: "You can add friends with their username.",
	  usernamePlaceholder: "Username",
	  block: "Block",
	  blockUserConfirmation: "Are you sure you want to block this <b>user</b>?<br/>Blocking this user will also remove them from your friends list.",
	  cancel: "Cancel",
	  noFriendsFound: "No friends found.",
	  userBlockedSuccess: "User {username} blocked successfully.",
	  userBlockFailed: "Failed to block user {username}.",
	  userBlockError: "Error blocking user {username}.",
	  friendRequestSentSuccess: "Friend request sent to {username} successfully.",
	  friendRequestSentFailed: "Failed to send friend request to {username}.",
	  friendRequestSentError: "Error sending friend request to {username}.",
	  connected: "Connected",
	  offline: "Offline",
	  message: "Message",
	  pending: "Pending",
	  noPendingFriendRequests: "No pending friend requests.",
	  friendRequestAccepted: "Friend request from {username} accepted",
	  friendRequestAcceptFailed: "Failed to accept friend request from {username}",
	  friendRequestAcceptError: "Error accepting friend request from {username}",
	  blocked: "Blocked",
	  noBlockedUsersFound: "No blocked users found.",
	  userUnblockedSuccess: "User {username} unblocked successfully.",
	  userUnblockFailed: "Failed to unblock user {username}.",
	  userUnblockError: "Error unblocking user {username}.",
	  messagePlaceholder: "Message",
	  you: "You",
		youInvitedForGame: "You invited for a game",
		youWereInvited: "Invited you for a game",
		failedLoadingChat: "Error, failed loading messages",
		chatLoadMore: "Load more",
		localGame: "Local game",
	  languages: {
      en: "🇬🇧 English",
      fr: "🇫🇷 Français",
      es: "🇪🇸 Español"
	  }
	},
	fr: {
	  title: "Accueil",
	  aiMaxPlayers: "Nombre maximum de joueurs IA atteint.",
	  lookForGame: "Rechercher un Jeu",
	  createGame: "Créer un Jeu",
	  createTournament: "Créer un Tournoi",
	  joinTournament: "Rejoindre un Tournoi",
	  aiOpponentDescription: "Par défaut, l'adversaire IA est réglé sur OFF",
	  online: "En ligne",
	  settingsGameTitle: "Paramètres du Jeu",
	  fastBallSpeed: "Vitesse de Balle Rapide",
	  aiOpponent: "Adversaire IA",
	  ballColor: "Couleur de la Balle",
	  black: "Noir",
	  blue: "Bleu",
	  red: "Rouge",
	  cancel: "Annuler",
	  play: "Jouer",
	  nickname: "Pseudo",
	  aiNickname: "Pseudo de l'IA",
	  title: "Transcendence",
	  profile: "Profil",
	  logout: "Déconnexion",
	  friends: "Amis",
	  pending: "En attente",
	  blocked: "Bloqués",
	  aiNicknameCannotBeEmpty: "Le pseudo de l'IA ne peut pas être vide.",
	  aiNicknameAlreadyUsed: "Ce pseudo d'IA est déjà utilisé. Veuillez en choisir un autre.",
	  invalidNicknameInput: "Entrée invalide : Le pseudo ne peut pas être le même que celui des IA.",
	  emptyNicknameError: "Entrée invalide : Le pseudo ne peut pas être vide",
	  serverError: "Entrée incorrecte ou erreur serveur. Veuillez réessayer.",
	  settingsGameTitle: "Paramètres du jeu",
	  nickname: "Pseudo",
	  enterNicknameForTournament: "Veuillez entrer un pseudo pour le tournoi",
	  fastBallSpeed: "Vitesse de balle rapide",
	  fastBallSpeedDescription: "Par défaut, la vitesse de la balle est réglée sur normal",
	  black: "Noir",
	  blue: "Bleu",
	  red: "Rouge",
	  ballColorDescription: "Par défaut, la couleur de la balle est réglée sur Noir",
	  aiPlayers: "Joueurs IA",
	  noAiPlayersAdded: "Aucun joueur IA ajouté. Ajoutez-en !",
      aiNickname: "Pseudo de l'IA",
	  enterNicknameForAi: "Veuillez entrer un pseudo pour l'IA",
	  cancel: "Annuler",
	  play: "Jouer",
	  next: "Suivant",
	  aiNicknameCannotBeEmpty: "Le pseudo de l'IA ne peut pas être vide.",
	  aiNicknameAlreadyUsed: "Ce pseudo d'IA est déjà utilisé. Veuillez en choisir un autre.",
	  invalidNicknameInput: "Entrée invalide : Le pseudo ne peut pas être le même que celui des IA.",
	  emptyNicknameError: "Entrée invalide : Le pseudo ne peut pas être vide",
	  serverError: "Entrée incorrecte ou erreur serveur. Veuillez réessayer.",
	  addFriendsTitle: "Vous pouvez ajouter des amis avec leur nom d'utilisateur.",
	  usernamePlaceholder: "Nom d'utilisateur",
	  block: "Bloquer",
	  blockUserConfirmation: "Êtes-vous sûr de vouloir bloquer cet <b>utilisateur</b> ?<br/>Bloquer cet utilisateur le supprimera également de votre liste d'amis.",
	  cancel: "Annuler",
	  noFriendsFound: "Aucun ami trouvé.",
	  userBlockedSuccess: "L'utilisateur {username} a été bloqué avec succès.",
	  userBlockFailed: "Échec du blocage de l'utilisateur {username}.",
	  userBlockError: "Erreur lors du blocage de l'utilisateur {username}.",
	  friendRequestSentSuccess: "Demande d'ami envoyée à {username} avec succès.",
	  friendRequestSentFailed: "Échec de l'envoi de la demande d'ami à {username}.",
	  friendRequestSentError: "Erreur lors de l'envoi de la demande d'ami à {username}.",
	  connected: "Connecté",
	  offline: "Hors ligne",
	  message: "Message",
	  pending: "En attente",
	  noPendingFriendRequests: "Aucune demande d'ami en attente.",
	  friendRequestAccepted: "Demande d'ami de {username} acceptée",
	  friendRequestAcceptFailed: "Échec de l'acceptation de la demande d'ami de {username}",
	  friendRequestAcceptError: "Erreur lors de l'acceptation de la demande d'ami de {username}",
	  blocked: "Bloqué",
	  noBlockedUsersFound: "Aucun utilisateur bloqué trouvé.",
	  userUnblockedSuccess: "L'utilisateur {username} a été débloqué avec succès.",
	  userUnblockFailed: "Échec du déblocage de l'utilisateur {username}.",
	  userUnblockError: "Erreur lors du déblocage de l'utilisateur {username}.",
	  messagePlaceholder: "Message",
	  you: "Vous",
		youInvitedForGame: "Vous avez invité pour un jeu",
		youWereInvited: "Vous avez été invité pour un jeu",
		failedLoadingChat: "Erreur de chargement des messages",
		chatLoadMore: "Charger plus de messages",
		localGame: "Jeu local",
	  languages: {
		en: "🇬🇧 Anglais",
		fr: "🇫🇷 Français",
		es: "🇪🇸 Espagnol"
		}

	},
	es: {
	  title: "Inicio",
	  aiMaxPlayers: "Se ha alcanzado el número máximo de jugadores IA.",
	  lookForGame: "Buscar un Juego",
	  createGame: "Crear Juego",
	  createTournament: "Crear Torneo",
	  joinTournament: "Unirse al Torneo",
	  online: "En línea",
	  settingsGameTitle: "Configuración del Juego",
	  fastBallSpeed: "Velocidad de Bola Rápida",
	  aiOpponentDescription: "Por defecto, el oponente IA está configurado en OFF",
	  aiOpponent: "Oponente IA",
	  ballColor: "Color de la Bola",
	  black: "Negro",
	  blue: "Azul",
	  red: "Rojo",
	  cancel: "Cancelar",
	  play: "Jugar",
	  nickname: "Apodo",
	  aiNickname: "Apodo de la IA",
	  title: "Transcendence",
	  profile: "Perfil",
	  logout: "Cerrar sesión",
	  friends: "Amigos",
	  pending: "Pendientes",
	  blocked: "Bloqueados",
	  aiNicknameCannotBeEmpty: "El apodo de la IA no puede estar vacío.",
	  aiNicknameAlreadyUsed: "Este apodo de IA ya está en uso. Por favor, elige otro.",
	  invalidNicknameInput: "Entrada no válida: El apodo no puede ser el mismo que los apodos de IA.",
	  emptyNicknameError: "Entrada no válida: El apodo no puede estar vacío",
	  serverError: "Entrada incorrecta o error del servidor. Por favor, inténtalo de nuevo.",
	  settingsGameTitle: "Configuración del juego",
	  nickname: "Apodo",
	  enterNicknameForTournament: "Por favor, ingrese un apodo para el torneo",
	  fastBallSpeed: "Velocidad rápida de la bola",
	  fastBallSpeedDescription: "Por defecto, la velocidad de la bola está configurada en normal",
	  black: "Negro",
	  blue: "Azul",
	  red: "Rojo",
	  ballColorDescription: "Por defecto, el color de la bola está configurado en Negro",
	  aiPlayers: "Jugadores IA",
	  noAiPlayersAdded: "No se han añadido jugadores IA. ¡Añade algunos!",
	  aiNickname: "Apodo de la IA",
	  enterNicknameForAi: "Por favor, ingrese un apodo para la IA",
	  cancel: "Cancelar",
	  play: "Jugar",
	  next: "Siguiente",
	  aiNicknameCannotBeEmpty: "El apodo de la IA no puede estar vacío.",
      aiNicknameAlreadyUsed: "Este apodo de IA ya está en uso. Por favor, elige otro.",
	  invalidNicknameInput: "Entrada no válida: El apodo no puede ser el mismo que los apodos de IA.",
	  emptyNicknameError: "Entrada no válida: El apodo no puede estar vacío",
	  serverError: "Entrada incorrecta o error del servidor. Por favor, inténtalo de nuevo.",
	  addFriendsTitle: "Puedes agregar amigos con su nombre de usuario.",
	  usernamePlaceholder: "Nombre de usuario",
	  block: "Bloquear",
	  blockUserConfirmation: "¿Estás seguro de que quieres bloquear a este <b>usuario</b>?<br/>Bloquear a este usuario también lo eliminará de tu lista de amigos.",
	  cancel: "Cancelar",
	  noFriendsFound: "No se encontraron amigos.",
	  userBlockedSuccess: "Usuario {username} bloqueado con éxito.",
	  userBlockFailed: "No se pudo bloquear al usuario {username}.",
	  userBlockError: "Error al bloquear al usuario {username}.",
	  friendRequestSentSuccess: "Solicitud de amistad enviada a {username} con éxito.",
	  friendRequestSentFailed: "No se pudo enviar la solicitud de amistad a {username}.",
	  friendRequestSentError: "Error al enviar la solicitud de amistad a {username}.",
	  connected: "Conectado",
	  offline: "Desconectado",
	  message: "Mensaje",
	  pending: "Pendiente",
	  noPendingFriendRequests: "No hay solicitudes de amistad pendientes.",
	  friendRequestAccepted: "Solicitud de amistad de {username} aceptada",
	  friendRequestAcceptFailed: "No se pudo aceptar la solicitud de amistad de {username}",
	  friendRequestAcceptError: "Error al aceptar la solicitud de amistad de {username}",
	  blocked: "Bloqueado",
	  noBlockedUsersFound: "No se encontraron usuarios bloqueados.",
	  userUnblockedSuccess: "Usuario {username} desbloqueado con éxito.",
	  userUnblockFailed: "No se pudo desbloquear al usuario {username}.",
	  userUnblockError: "Error al desbloquear al usuario {username}.",
	  messagePlaceholder: "Mensaje",
	  you: "Tú",
		youInvitedForGame: "Te invitó a un juego",
    youWereInvited: "Te ha invitado a un juego",
    failedLoadingChat: "Error, no se pudieron cargar los mensajes",
    	chatLoadMore: "Cargar más",
		localGame: "Juego local",
	  languages: {
		en: "🇬🇧 Inglés",
		fr: "🇫🇷 Francés",
		es: "🇪🇸 Español"
    	}
	}
  };

  //--------------------------ProfilePAck--------------------------------//

  export const profile = {
	en: {
	  editProfile: "Edit Profile",
	  profilePicture: "Profile Picture",
	  firstName: "First Name",
	  lastName: "Last Name",
	  cancel: "Cancel",
	  saveChanges: "Save changes",
	  fillAllFields: "Please fill in all fields correctly",
	  incorrectInput: "Incorrect input, please try again.",
	  profileUpdateSuccess: "User profile updated successfully",
	  profileUpdateError: "Error updating user profile",
	  matchHistory: "Match History",
	  wins: "Wins",
	  losses: "Losses",
	  fetchProfileFailed: "Failed to fetch user profile",
	  fetchProfileError: "Error fetching user profile",
	  matchHistory: "Match History",
	  fetchMatchHistoryFailed: "Failed to fetch match history",
	  fetchMatchHistoryError: "Error fetching match history",
	  noMatchesPlayed: "The court is empty... for now. How about playing your first game?",
	  victory: "Victory",
	  defeat: "Defeat",
	  profilePicture: "Profile Picture",
	  status: "Status",
	  connected: "Connected",
	  offline: "Offline",
	  totalGames: "Total Games",
	  errorLoadingFriendProfile: "Error loading friend profile",
	  errorLoadingFriendMatchHistory: "Error loading friend match history",
	  victory: "Victory",
	  defeat: "Defeat",
	  profilePicture: "Profile Picture",
	  friendUsernameNotSet: "Friend username not set",
	
	},
	fr: {
	  editProfile: "Modifier le profil",
	  profilePicture: "Photo de profil",
	  firstName: "Prénom",
	  lastName: "Nom",
	  cancel: "Annuler",
	  saveChanges: "Enregistrer les modifications",
	  fillAllFields: "Veuillez remplir correctement tous les champs",
	  incorrectInput: "Saisie incorrecte, veuillez réessayer.",
	  profileUpdateSuccess: "Profil utilisateur mis à jour avec succès",
	  profileUpdateError: "Erreur lors de la mise à jour du profil utilisateur",
	  matchHistory: "Historique des matchs",
	  wins: "Victoires",
	  losses: "Défaites",
	  fetchProfileFailed: "Échec de la récupération du profil utilisateur",
	  fetchProfileError: "Erreur lors de la récupération du profil utilisateur",
	  matchHistory: "Historique des matchs",
	  fetchMatchHistoryFailed: "Échec de la récupération de l'historique des matchs",
	  fetchMatchHistoryError: "Erreur lors de la récupération de l'historique des matchs",
	  noMatchesPlayed: "Le terrain est vide... pour l'instant. Que diriez-vous de jouer votre première partie ?",
	  victory: "Victoire",
	  defeat: "Défaite",
	  profilePicture: "Photo de profil",
	  status: "Statut",
	  connected: "Connecté",
	  offline: "Hors ligne",
	  totalGames: "Total des parties",
	  errorLoadingFriendProfile: "Erreur lors du chargement du profil de l'ami",
	  errorLoadingFriendMatchHistory: "Erreur lors du chargement de l'historique des matchs de l'ami",
	  victory: "Victoire",
	  defeat: "Défaite",
	  profilePicture: "Photo de profil",
	  friendUsernameNotSet: "Nom d'utilisateur de l'ami non défini"
	},
	es: {
	  editProfile: "Editar perfil",
	  profilePicture: "Foto de perfil",
	  firstName: "Nombre",
	  lastName: "Apellido",
	  cancel: "Cancelar",
	  saveChanges: "Guardar cambios",
	  fillAllFields: "Por favor, rellene todos los campos correctamente",
	  incorrectInput: "Entrada incorrecta, por favor inténtelo de nuevo.",
	  profileUpdateSuccess: "Perfil de usuario actualizado con éxito",
	  profileUpdateError: "Error al actualizar el perfil de usuario",
	  matchHistory: "Historial de partidos",
	  wins: "Victorias",
	  losses: "Derrotas",
	  fetchProfileFailed: "No se pudo obtener el perfil del usuario",
	  fetchProfileError: "Error al obtener el perfil del usuario",
	  matchHistory: "Historial de partidos",
	  fetchMatchHistoryFailed: "No se pudo obtener el historial de partidos",
	  fetchMatchHistoryError: "Error al obtener el historial de partidos",
	  noMatchesPlayed: "La cancha está vacía... por ahora. ¿Qué tal si juegas tu primer partido?",
	  victory: "Victoria",
	  defeat: "Derrota",
	  profilePicture: "Foto de perfil",
	  status: "Estado",
	  connected: "Conectado",
	  offline: "Desconectado",
	  totalGames: "Total de partidos",
	  errorLoadingFriendProfile: "Error al cargar el perfil del amigo",
	  errorLoadingFriendMatchHistory: "Error al cargar el historial de partidos del amigo",
	  victory: "Victoria",
	  defeat: "Derrota",
	  profilePicture: "Foto de perfil",
	  friendUsernameNotSet: "Nombre de usuario del amigo no establecido"
	}
  };