export const home = {
	en: {
	  title: "Home",
	  createTournament: "Create Tournament",
	  joinTournament: "Join Tournament",
	  online: "Online",
	  settingsGameTitle: "Settings of the Game",
	  fastBallSpeed: "Fast Ball Speed",
	  aiOpponent: "AI Opponent",
	  ballColor: "Ball Color",
	  black: "Black",
	  blue: "Blue",
	  red: "Red",
	  cancel: "Cancel",
	  play: "Play",
	  nickname: "Nickname",
	  aiNickname: "AI Nickname",
	  title: "Transcendence",
	  profile: "Profile",
	  logout: "Logout",
	  friends: "Friends",
	  pending: "Pending",
	  blocked: "Blocked",
	  languages: {
      en: "🇬🇧 English",
      fr: "🇫🇷 Français",
      es: "🇪🇸 Español"
	  }
	},
	fr: {
	  title: "Accueil",
	  createTournament: "Créer un Tournoi",
	  joinTournament: "Rejoindre un Tournoi",
	  online: "En ligne",
	  settingsGameTitle: "Paramètres du Jeu",
	  fastBallSpeed: "Vitesse de Balle Rapide",
	  aiOpponent: "Adversaire IA",
	  ballColor: "Couleur de la Balle",
	  black: "Noir",
	  blue: "Bleu",
	  red: "Rouge",
	  cancel: "Annuler",
	  play: "Jouer",
	  nickname: "Pseudo",
	  aiNickname: "Pseudo de l'IA",
	  title: "Transcendence",
	  profile: "Profil",
	  logout: "Déconnexion",
	  friends: "Amis",
	  pending: "En attente",
	  blocked: "Bloqués",
	  languages: {
		en: "🇬🇧 Anglais",
		fr: "🇫🇷 Français",
		es: "🇪🇸 Espagnol"
		}

	},
	es: {
	  title: "Inicio",
	  createTournament: "Crear Torneo",
	  joinTournament: "Unirse al Torneo",
	  online: "En línea",
	  settingsGameTitle: "Configuración del Juego",
	  fastBallSpeed: "Velocidad de Bola Rápida",
	  aiOpponent: "Oponente IA",
	  ballColor: "Color de la Bola",
	  black: "Negro",
	  blue: "Azul",
	  red: "Rojo",
	  cancel: "Cancelar",
	  play: "Jugar",
	  nickname: "Apodo",
	  aiNickname: "Apodo de la IA",
	  title: "Transcendence",
	  profile: "Perfil",
	  logout: "Cerrar sesión",
	  friends: "Amigos",
	  pending: "Pendientes",
	  blocked: "Bloqueados",
	  languages: {
		en: "🇬🇧 Inglés",
		fr: "🇫🇷 Francés",
		es: "🇪🇸 Español"
    	}
	}
  };